spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

info:
  app: Discovery
  description: Servidor Eureka
  version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health, info

server:
  port: 8761

