spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true         # Habilita descubrimiento dinámico vía Eureka
          lower-case-service-id: true  # Convierte los IDs de los servicios a minúsculas

      routes:
        - id: frontend-service
          uri: lb://fronted-service   # <- ¡IMPORTANTE! Usa 'lb://' para usar el nombre registrado en Eureka
          predicates:
            - Path=/**
          filters:
            - StripPrefix=1

        - id: users-service
          uri: lb://users-service   # <- ¡IMPORTANTE! Usa 'lb://' para usar el nombre registrado en Eureka
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=1

        - id: orders-service
          uri: lb://orders-service  # <- También se accede por el nombre en Eureka
          predicates:
            - Path=/api/pedidos/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
